// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATUS-0]
	_ = x[CONNECT-1]
	_ = x[SEARCH-2]
	_ = x[DOWNLOAD-3]
	_ = x[RATELIMIT-4]
	_ = x[RENAME_PROMPT-5]
	_ = x[RENAME_CONFIRM-6]
	_ = x[DOWNLOAD_WAITING-7]
	_ = x[DOWNLOAD_STARTED-8]
	_ = x[POST_PROCESS_STARTED-9]
	_ = x[STAGED_BOOKS_NOTIFY-10]
	_ = x[STAGED_BOOK_RESUME-11]
	_ = x[STAGED_QUEUE_LATER-12]
	_ = x[SERIES_AUTOCOMPLETE-13]
	_ = x[PROCESS_STAGED_BOOKS-14]
	_ = x[DELETE_STAGED-15]
	_ = x[GET_STAGED_LIST-16]
	_ = x[STAGED_BOOKS_LIST-17]
	_ = x[PROCESS_ONE_STAGED-18]
	_ = x[HISTORY_LIST-19]
	_ = x[HISTORY_DELETE-20]
	_ = x[HISTORY_CLEAR-21]
	_ = x[SERVER_LIST-22]
	_ = x[DOWNLOAD_FAILED-23]
	_ = x[FILE_CONFLICT-24]
	_ = x[IRC_SEND-25]
	_ = x[IRC_MESSAGE-26]
	_ = x[IRC_SUBSCRIBE-27]
}

const _MessageType_name = "STATUSCONNECTSEARCHDOWNLOADRATELIMITRENAME_PROMPTRENAME_CONFIRMDOWNLOAD_WAITINGDOWNLOAD_STARTEDPOST_PROCESS_STARTEDSTAGED_BOOKS_NOTIFYSTAGED_BOOK_RESUMESTAGED_QUEUE_LATERSERIES_AUTOCOMPLETEPROCESS_STAGED_BOOKSDELETE_STAGEDGET_STAGED_LISTSTAGED_BOOKS_LISTPROCESS_ONE_STAGEDHISTORY_LISTHISTORY_DELETEHISTORY_CLEARSERVER_LISTDOWNLOAD_FAILEDFILE_CONFLICTIRC_SENDIRC_MESSAGEIRC_SUBSCRIBE"

var _MessageType_index = [...]uint16{0, 6, 13, 19, 27, 36, 49, 63, 79, 95, 115, 134, 152, 170, 189, 209, 222, 237, 254, 272, 284, 298, 311, 322, 337, 350, 358, 369, 382}

func (i MessageType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MessageType_index)-1 {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[idx]:_MessageType_index[idx+1]]
}
