// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATUS-0]
	_ = x[CONNECT-1]
	_ = x[SEARCH-2]
	_ = x[DOWNLOAD-3]
	_ = x[RATELIMIT-4]
	_ = x[RENAME_PROMPT-5]
	_ = x[RENAME_CONFIRM-6]
	_ = x[DOWNLOAD_WAITING-7]
	_ = x[DOWNLOAD_STARTED-8]
	_ = x[POST_PROCESS_STARTED-9]
	_ = x[STAGED_BOOKS_NOTIFY-10]
	_ = x[STAGED_BOOK_RESUME-11]
	_ = x[STAGED_QUEUE_LATER-12]
	_ = x[SERIES_AUTOCOMPLETE-13]
	_ = x[PROCESS_STAGED_BOOKS-14]
}

const _MessageType_name = "STATUSCONNECTSEARCHDOWNLOADRATELIMITrename_promptrename_confirmdownload_waitingdownload_startedpost_process_startedstagd_books_notifystaged_book_resumestaged_queue_laterseries_autocompleteprocess_staged_books"

// index offsets (chars): STATUS=6 CONNECT=13 SEARCH=19 DOWNLOAD=27 RATELIMIT=36
// rename_prompt=49 rename_confirm=63 download_waiting=79 download_started=95
// post_process_started=115 staged_books_notify=133 staged_book_resume=151
// staged_queue_later=169 series_autocomplete=188 process_staged_books=208
// (Note: "stagd_books_notify" in name string is the 18-char display; compile check is authoritative)
var _MessageType_index = [...]uint8{0, 6, 13, 19, 27, 36, 49, 63, 79, 95, 115, 133, 151, 169, 188, 208}

func (i MessageType) String() string {
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
