// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATUS-0]
	_ = x[CONNECT-1]
	_ = x[SEARCH-2]
	_ = x[DOWNLOAD-3]
	_ = x[RATELIMIT-4]
	_ = x[RENAME_PROMPT-5]
	_ = x[RENAME_CONFIRM-6]
	_ = x[DOWNLOAD_WAITING-7]
	_ = x[DOWNLOAD_STARTED-8]
	_ = x[POST_PROCESS_STARTED-9]
	_ = x[STAGED_BOOKS_NOTIFY-10]
	_ = x[STAGED_BOOK_RESUME-11]
	_ = x[STAGED_QUEUE_LATER-12]
	_ = x[SERIES_AUTOCOMPLETE-13]
	_ = x[PROCESS_STAGED_BOOKS-14]
	_ = x[DELETE_STAGED-15]
	_ = x[GET_STAGED_LIST-16]
	_ = x[STAGED_BOOKS_LIST-17]
	_ = x[PROCESS_ONE_STAGED-18]
	_ = x[HISTORY_LIST-19]
	_ = x[HISTORY_DELETE-20]
	_ = x[HISTORY_CLEAR-21]
}

const _MessageType_name = "STATUSCONNECTSEARCHDOWNLOADRATELIMITrename_promptrename_confirmdownload_waitingdownload_startedpost_process_startedstagd_books_notifystaged_book_resumestaged_queue_laterseries_autocompleteprocess_staged_booksdelete_stagedget_staged_liststaged_books_listprocess_one_stagedhistory_listhistory_deletehistory_clear"

// offsets: ...process_one_staged=272, history_list=284, history_delete=298, history_clear=311
var _MessageType_index = [...]uint16{0, 6, 13, 19, 27, 36, 49, 63, 79, 95, 115, 133, 151, 169, 188, 208, 221, 236, 253, 272, 284, 298, 311}

func (i MessageType) String() string {
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
